### ISSUE TITLE
CI Deprecation Warning

### ISSUE THREAD

**Issue by aaruni96** [oscar-system/TutorialTesterforOscar#1]
`::set-output` is deprecated. Figure out how to fix it.

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by HereAround** [comment]
@aaruni96 Is this still relevant? Or can this be closed?

**Comment by aaruni96** [comment]
Its relevant as in, we should fix it before whenever github disables ::set-output, but it works for now, and is not on the top of my to-do list.

**Comment by aaruni96** [comment]
Fixed by 411fac20e802e6613b3f7a411216bff70e4c8bc5

**Comment by HereAround** [comment]
As of https://github.com/oscar-system/TutorialTesterforOscar/actions/runs/10190862135, the issue seems to persist.

@aaruni96, I think this issue needs to be opened again. (I cannot do this. Not enough rights, I should guess.)

**Comment by aaruni96** [comment]
That's a different depreciation warning, and ~~nothing we can do about, just wait for the people at julia-actions to update the julia action thingy~~

Looks like Julia-actions updated to version 2 and we can do that too. Thanks for making me take a second look!
